# Generated by Django 5.2.10 on 2026-01-23 15:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_patients', to=settings.AUTH_USER_MODEL, verbose_name='Usuario asignado'),
        ),
        migrations.AlterField(
            model_name='attachment',
            name='type',
            field=models.CharField(choices=[('CREDENCIAL', 'Credencial'), ('DNI', 'DNI'), ('ORDEN', 'Orden de intervención'), ('MATERIALES', 'Materiales'), ('ESTUDIOS', 'Estudios / HC'), ('ESTUDIOS', 'Autorizacion')], max_length=20),
        ),
    ]
