# Generated by Django 5.2.10 on 2026-01-26 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_patient_assigned_to_delete_patienthistory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='status',
            field=models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('SOLICITADO', 'Solicitado'), ('AUTORIZADO', 'Autorizado'), ('MATERIAL_PENDIENTE', 'Material pendiente'), ('RECHAZO', 'Rechazo'), ('REPROGRAMADO', 'Reprogramado'), ('REALIZADO', 'Realizado')], default='PENDIENTE', max_length=30),
        ),
    ]
