# Generated by Django 5.0.2 on 2026-02-09 13:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_patient_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('CREATE', 'Creado'), ('UPDATE', 'Actualizado'), ('DELETE', 'Eliminado')], default='UPDATE', max_length=10)),
                ('field_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Campo')),
                ('old_value', models.TextField(blank=True, null=True, verbose_name='Valor anterior')),
                ('new_value', models.TextField(blank=True, null=True, verbose_name='Valor nuevo')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Fecha y hora')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='core.patient')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Historial de cambio',
                'verbose_name_plural': 'Historial de cambios',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='SavedFilter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre del filtro')),
                ('filter_params', models.JSONField(verbose_name='Parámetros')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_default', models.BooleanField(default=False, verbose_name='Filtro por defecto')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_filters', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Filtro guardado',
                'verbose_name_plural': 'Filtros guardados',
                'ordering': ['-is_default', 'name'],
                'unique_together': {('user', 'name')},
            },
        ),
    ]
