# Generated by Django 5.0.2 on 2026-02-11 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_patienthistory_savedfilter'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='sede',
            field=models.CharField(blank=True, choices=[('', 'Sin especificar'), ('SAAVEDRA', 'Saavedra'), ('POMBO', 'Pombo'), ('LAS HERAS', 'Las Heras')], default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='attachment',
            name='type',
            field=models.CharField(choices=[('CREDENCIAL', 'Credencial'), ('DNI', 'DNI'), ('ORDEN', 'Orden de intervención'), ('MATERIALES', 'Materiales'), ('ESTUDIOS', 'Estudios / HC')], max_length=20),
        ),
    ]
