# Generated by Django 5.2.10 on 2026-02-11 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_patient_sede_alter_attachment_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='surgery_time',
            field=models.TimeField(blank=True, null=True, verbose_name='Hora de cirugía'),
        ),
    ]
