# Generated by Django 5.2.10 on 2026-02-13 03:52

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_patient_surgery_time'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='attachment',
            name='type',
            field=models.CharField(choices=[('CREDENCIAL', 'Credencial'), ('DNI', 'DNI'), ('ORDEN', 'Orden de intervención'), ('AUTORIZACION', 'Autorización'), ('MATERIALES', 'Materiales'), ('ESTUDIOS', 'Estudios / HC')], max_length=20),
        ),
        migrations.AddIndex(
            model_name='patient',
            index=models.Index(fields=['planned_date'], name='patient_planned_date_idx'),
        ),
        migrations.AddIndex(
            model_name='patient',
            index=models.Index(fields=['status'], name='patient_status_idx'),
        ),
        migrations.AddIndex(
            model_name='patient',
            index=models.Index(fields=['service'], name='patient_service_idx'),
        ),
        migrations.AddIndex(
            model_name='patient',
            index=models.Index(fields=['doctor'], name='patient_doctor_idx'),
        ),
        migrations.AddIndex(
            model_name='patient',
            index=models.Index(fields=['coverage'], name='patient_coverage_idx'),
        ),
        migrations.AddIndex(
            model_name='patient',
            index=models.Index(fields=['created_at'], name='patient_created_at_idx'),
        ),
        migrations.AddIndex(
            model_name='patient',
            index=models.Index(fields=['planned_date', 'status'], name='patient_date_status_idx'),
        ),
    ]
