# Generated by Django 5.2.10 on 2026-02-13 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_attachment_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='status',
            field=models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('SOLICITADO', 'Solicitado'), ('AUTORIZADO', 'Autorizado'), ('PRESUPUESTO_SI', 'Presupuesto sí'), ('MATERIAL_PENDIENTE', 'Material pendiente'), ('RECHAZO', 'Rechazo'), ('REPROGRAMADO', 'Reprogramado'), ('REALIZADO', 'Realizado')], default='PENDIENTE', max_length=30),
        ),
    ]
