# Generated by Django 5.0.2 on 2026-03-06 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_add_normalized_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='en_quirofano',
            field=models.BooleanField(default=False, verbose_name='En quirófano'),
        ),
        migrations.AddField(
            model_name='patient',
            name='material_status',
            field=models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('AUTORIZADO', 'Autorizado'), ('RECHAZADO', 'Rechazado por profesional')], default='PENDIENTE', max_length=20, verbose_name='Estado de material'),
        ),
        migrations.AddField(
            model_name='patient',
            name='observaciones_calendario',
            field=models.TextField(blank=True, null=True, verbose_name='Observaciones del calendario'),
        ),
    ]
