# Generated by Django 5.0.2 on 2026-04-02 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_quirofanoentry_workflow_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='quirofanoentry',
            options={'ordering': ['surgery_date', 'quirofano_number', 'surgery_time', 'patient_name'], 'verbose_name': 'Entrada de quirófano', 'verbose_name_plural': 'Entradas de quirófano'},
        ),
        migrations.AddField(
            model_name='quirofanoentry',
            name='estado_autorizacion',
            field=models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('AUTORIZADO', 'Autorizado'), ('RECHAZADO', 'Rechazado'), ('NO_APLICA', 'No aplica')], default='PENDIENTE', max_length=20, verbose_name='Estado de autorización'),
        ),
        migrations.AddField(
            model_name='quirofanoentry',
            name='estado_material',
            field=models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('OK', 'OK'), ('NO_APLICA', 'No aplica')], default='PENDIENTE', max_length=20, verbose_name='Estado de material'),
        ),
        migrations.AddField(
            model_name='quirofanoentry',
            name='estado_presupuesto',
            field=models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('APROBADO', 'Aprobado'), ('PENDIENTE_PAGO', 'Pend. pago'), ('NO_APLICA', 'No aplica')], default='PENDIENTE', max_length=20, verbose_name='Estado de presupuesto'),
        ),
        migrations.AddField(
            model_name='quirofanoentry',
            name='observaciones',
            field=models.TextField(blank=True, default='', verbose_name='Observaciones'),
        ),
        migrations.AddField(
            model_name='quirofanoentry',
            name='quirofano_number',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='Nro. quirófano'),
        ),
        migrations.AddIndex(
            model_name='quirofanoentry',
            index=models.Index(fields=['surgery_date', 'quirofano_number'], name='quirof_date_qnumber_idx'),
        ),
    ]
