# Generated by Django 5.0.2 on 2026-04-02 04:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_add_quirofano_gestion_fields'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='quirofanoentry',
            options={'ordering': ['surgery_date', 'surgery_time', 'patient_name'], 'verbose_name': 'Entrada de quirófano', 'verbose_name_plural': 'Entradas de quirófano'},
        ),
        migrations.RemoveIndex(
            model_name='quirofanoentry',
            name='quirof_date_qnumber_idx',
        ),
        migrations.RemoveField(
            model_name='quirofanoentry',
            name='estado_autorizacion',
        ),
        migrations.RemoveField(
            model_name='quirofanoentry',
            name='estado_material',
        ),
        migrations.RemoveField(
            model_name='quirofanoentry',
            name='estado_presupuesto',
        ),
        migrations.RemoveField(
            model_name='quirofanoentry',
            name='observaciones',
        ),
        migrations.RemoveField(
            model_name='quirofanoentry',
            name='quirofano_number',
        ),
    ]
