# Generated by Django 5.0.2 on 2026-05-07 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_add_status_suspendida'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='impreso',
            field=models.BooleanField(default=False, verbose_name='Impreso'),
        ),
    ]
